name: Build Configurator GUI

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'ConfiguratorGUI/**'
      - 'APODWallpaper/**' # Trigger if the dependency changes
      - 'Directory.Build.props'
      - 'APODWallpaper.slnx'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'ConfiguratorGUI/**'

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

    - name: Setup .NET 10
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
      with:
        dotnet-version: '10.0.x'

    - name: Run Tests
      run: dotnet test APODTesting/APODTesting.csproj --configuration Release -p:Patch=${{ github.run_number }}

    - name: Publish Configurator GUI
      # Compiles and publishes just the GUI project
      run: dotnet publish ConfiguratorGUI/ConfiguratorGUI.csproj --configuration Release -p:Patch=${{ github.run_number }} --output ./artifacts/ConfiguratorGUI

    - name: Upload Build Artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
      with:
        name: ConfiguratorGUI-v${{ github.run_number }}
        path: ./artifacts/ConfiguratorGUI